### PR TITLE
fix: login screen issues

### LINKED ISSUE #68: app: Login screen
image
image

Headline is too long. Also: shouldn't it be "Öppna Skolplattformen"?
Open BankID-button has slipped back behind keyboard (iOS)

### PR DESCRIPTION
**Pull request by believer**
This PR adds a couple of fixes to the login screen:

- Handle the title not wrapping correctly by adding `adjustFontSizeToFit`
- Change title to "Öppna Skolplattformen"
- Add call to `Keyboard.dismiss` which hides the keyboard when clicking outside
- Remove easter egg navigation when clicking on the image
- Flexbox fix to make `<KeyboardAvoidingView>` work correctly

Fixes #68

### CODE REVIEW

File: packages/app/components/login.component.js [hunk 1]
```diff
@@ -143,138 +145,153 @@ export const Login = ({navigation}) => {
...
-              style={{color: '#9CA3AF', marginTop: 4, marginBottom: 20}}>
-              Det {argument} alternativet
-            </Text>
-            {isFemale ? (
-              <Image
-                source={require('../assets/kvinna.png')}
-                style={{maxHeight: 300, width: '100%'}}
-              />
+      <TouchableWithoutFeedback onPress={Keyboard.dismiss}>
+        <SafeAreaView style={{flex: 1, backgroundColor: '#fff'}}>
```
Comment (ErikHellman) [inline packages/app/components/login.component.js:149]: Jag _tror_ att flex måste sitta på elementet direkt under `KeyboardAvoidingView`
